version: "3.9"

services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    depends_on:
      - mariadb
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/jbuan/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/jbuan/data/db
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
